src/main/java/de/adesso/kicker/user/User.java

Add equals() and hashCode() to User

---

src/main/java/de/adesso/kicker/configurations/MvcConfig.java
src/main/java/de/adesso/kicker/match/MatchController.java
src/main/java/de/adesso/kicker/match/MatchRepository.java
src/main/java/de/adesso/kicker/match/MatchService.java
src/main/java/de/adesso/kicker/user/UserController.java
src/main/java/de/adesso/kicker/user/UserRepository.java
src/main/java/de/adesso/kicker/user/UserService.java

Remove useless JavaDoc comments
Closes #23

Remove unnecessary JavaDocs

---

src/main/java/de/adesso/kicker/user/exception/UserAlreadyExistsException.java
src/main/java/de/adesso/kicker/user/exception/UserNotFoundException.java
src/main/java/de/adesso/kicker/user/exception/UserNotLoggedInException.java

Remove serialVersionUID from Exceptions

---

src/main/java/de/adesso/kicker/site/HomeController.java
src/main/java/de/adesso/kicker/site/ImpressumController.java

Split SiteController to HomeController and ImpressumController.

---

src/main/java/de/adesso/kicker/match/MatchController.java
src/main/java/de/adesso/kicker/user/UserController.java

Add BasePath to MatchController and UserController

---

src/main/java/de/adesso/kicker/user/UserController.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Add UserControllerTest

---

src/main/java/de/adesso/kicker/user/UserService.java
src/main/java/de/adesso/kicker/user/exception/UserDoesNotExistException.java

Remove UserDoesNotExistException

---

src/main/java/de/adesso/kicker/user/UserController.java
src/main/java/de/adesso/kicker/user/UserService.java
src/main/java/de/adesso/kicker/user/exception/UserNotFoundException.java

Add StatusCode Annotation, check->getUser

---

src/main/java/de/adesso/kicker/user/exception/UserNotFoundException.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Given/When/Then for UserServiceTest

---

formatting-rules.xml
src/main/java/de/adesso/kicker/configurations/KeycloakSecurityConfig.java
src/main/java/de/adesso/kicker/user/UserService.java
src/test/java/de/adesso/kicker/match/MatchControllerTest.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java

Update formatting rules and apply them

---

src/main/java/de/adesso/kicker/user/User.java
src/main/java/de/adesso/kicker/user/UserController.java
src/main/java/de/adesso/kicker/user/UserRepository.java
src/main/java/de/adesso/kicker/user/UserService.java
src/main/java/de/adesso/kicker/user/exception/UserAlreadyExistsException.java
src/main/java/de/adesso/kicker/user/exception/UserNotLoggedInException.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java
src/test/java/de/adesso/kicker/user/UserDummy.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Refactor user package and tests

---

src/main/java/de/adesso/kicker/match/MatchRepository.java
src/main/java/de/adesso/kicker/match/MatchService.java
src/test/java/de/adesso/kicker/match/MatchControllerTest.java
src/test/java/de/adesso/kicker/match/MatchDummy.java
src/test/java/de/adesso/kicker/match/MatchServiceTest.java

Fix #63 
Fix #61
Also changed/updated some other things like using `findById()` provided by `CrudRepository` and using `orElseThrow` on the optional.
Also updated the naming in `MatchDummy`.

Fix some problems in match package and tests

---

src/main/java/de/adesso/kicker/match/Match.java

Fix getPlayers(), getLosers() and getWinners() ocasionally adding null to lists

---

src/main/java/de/adesso/kicker/ranking/KFactor.java
src/main/java/de/adesso/kicker/ranking/Outcome.java
src/main/java/de/adesso/kicker/ranking/Ranking.java
src/main/java/de/adesso/kicker/ranking/RankingRepository.java
src/main/java/de/adesso/kicker/ranking/RankingService.java
src/main/java/de/adesso/kicker/ranking/RatingRange.java
src/main/java/de/adesso/kicker/user/User.java
src/main/java/de/adesso/kicker/user/UserService.java
src/main/resources/templates/user/profile.html
src/test/java/de/adesso/kicker/match/MatchDummy.java
src/test/java/de/adesso/kicker/ranking/RankingDummy.java
src/test/java/de/adesso/kicker/ranking/RankingServiceTest.java
src/test/java/de/adesso/kicker/user/UserDummy.java

Implement ranking API

---

src/main/java/de/adesso/kicker/user/UserService.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Now every time a user logs in successfully it is checked whether the user
exists or not. And if the user does not exist a new one is created and saved
in the database.
With this the `getLoggedInUser()` function could be simplified which closes #17
as it now only returns the current user and no longer create one in case a
`UserNotFoundException` was thrown.

Add EventListener for AuthenticationSuccessEvents

---

src/main/java/de/adesso/kicker/notification/matchverificationrequest/service/VerifyMatchService.java
src/main/java/de/adesso/kicker/notification/message/persistence/MessageType.java
src/main/java/de/adesso/kicker/site/controller/HomeController.java
src/main/java/de/adesso/kicker/user/persistence/UserRepository.java
src/main/java/de/adesso/kicker/user/service/UserService.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Also remove `findUserByEmail` which closes #91.

Add function to get a list of users sorted by rating

---

src/main/java/de/adesso/kicker/events/match/MatchVerificationSentEvent.java
src/main/java/de/adesso/kicker/notification/matchverificationrequest/persistence/MatchVerificationRequestRepository.java
src/main/java/de/adesso/kicker/notification/matchverificationrequest/service/VerifyMatchService.java

MatchVerificationRequest is saved.
Deleted getRequestByMatchAndReceiver in service and repo
Closes#89

Implemented MatchVerificationSentEvent that is sent when an

---

src/main/java/de/adesso/kicker/ranking/persistence/RankingRepository.java
src/main/java/de/adesso/kicker/ranking/service/RankingService.java
src/main/java/de/adesso/kicker/site/controller/HomeController.java

It should now be possible to combine /ranking to the backend.
References #87

Add option to use pagination in /ranking

---

src/main/java/de/adesso/kicker/notification/matchverificationrequest/persistence/MatchVerificationRequest.java

Added default constructor to MatchVerificationRequest

---

pom.xml
src/main/java/de/adesso/kicker/configurations/EmailConfig.java
src/main/java/de/adesso/kicker/email/EmailService.java
src/main/java/de/adesso/kicker/user/persistence/User.java
src/main/resources/application.properties
src/main/resources/messages.properties

Email Support is pretty much done, just waiting for Events.

Email implementation

---

src/main/java/de/adesso/kicker/match/service/MatchService.java

Add updateStatistics for users

---

src/main/java/de/adesso/kicker/email/EmailService.java
src/main/resources/templates/sites/matchresult.html

Adjust email message and form properties for matchresult.html

---

src/main/resources/templates/fragments/header.html

Disabled menus if user is not logged in

---

src/main/java/de/adesso/kicker/email/EmailService.java
src/test/java/de/adesso/kicker/email/EmailServiceTest.java

+ adapted test for EmailService
+ refactored EmailService

Improved test for EmailService

---

src/test/java/de/adesso/kicker/user/UserServiceTest.java

The tests checks whether the expected list of users is returned.

Add missing test for getUserPageSortedByRating()

---

src/test/java/de/adesso/kicker/ranking/RankingServiceTest.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java

Add missing test to check if the correct rank is returned.

Add test for getPositionOfPlayer()

---

src/test/java/de/adesso/kicker/events/MatchCreatedEventDummy.java
src/test/java/de/adesso/kicker/match/MatchDummy.java
src/test/java/de/adesso/kicker/notification/NotificationServiceTest.java
src/test/java/de/adesso/kicker/notification/matchverificationrequest/VerifyMatchServiceTest.java
src/test/java/de/adesso/kicker/notification/message/SendMessageServiceTest.java

Add several tests for cases that haven't been tested yet.

Add missing tests for notifications

---

src/main/resources/templates/fragments/header.html

Created login button in header

---

src/main/resources/application-integration-test.properties
src/test/java/de/adesso/kicker/match/MatchControllerIntegrationTest.java
src/test/resources/data.sql

The test checks if the normal case of adding a match works properly and interacts with all other services correctly.

Add integration test for add matches

---

src/main/resources/templates/sites/ranking.html

next: last player is on site
previous: actual site is the first site
Closes#133

Disabled pagination buttons if

---

src/main/java/de/adesso/kicker/notification/controller/NotificationController.java
src/main/java/de/adesso/kicker/user/controller/UserController.java
src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/sites/notificationresult.html
src/test/java/de/adesso/kicker/notification/NotificationControllerTest.java

Notification page

---

src/main/java/de/adesso/kicker/ranking/persistence/Ranking.java
src/main/java/de/adesso/kicker/ranking/service/RankingService.java
src/test/java/de/adesso/kicker/match/MatchDummy.java
src/test/java/de/adesso/kicker/ranking/RankingServiceTest.java

General refactoring of the ranking package.
* Tried to improve code readability
* Improved rating calculations
* Added some documentation

Refactor RankingService and related test

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/sites/matchresult.html
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html

based on: https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4

Reworked naming and error messages

---

src/main/resources/static/css/ranking.less

Change to a pointer when hovering over table

---

src/main/java/de/adesso/kicker/user/controller/UserController.java

Fixed profile site crash when current user is not logged in

---

src/main/resources/static/js/notifications.js
src/main/resources/templates/fragments/header.html

no-notification div gets applied if notification list gets emptied

---

src/test/java/de/adesso/kicker/user/UserControllerTest.java

The tests check whether the sites behave as expected when a user is not
logged in or the search user does not exist.

Add tests for user profiles

---

src/main/java/de/adesso/kicker/ranking/service/RankingService.java
src/main/java/de/adesso/kicker/site/controller/HomeController.java
src/main/java/de/adesso/kicker/user/persistence/User.java
src/main/java/de/adesso/kicker/user/persistence/UserRepository.java
src/main/java/de/adesso/kicker/user/service/UserService.java
src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html
src/test/java/de/adesso/kicker/site/controller/HomeControllerTest.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java
src/test/java/de/adesso/kicker/user/UserDummy.java
src/test/java/de/adesso/kicker/user/UserServiceTest.java

Functions that relied on users having a ranking have been updated
and templates are now checking if the given user has a ranking or not.
Tests have been updated and a new test to check if the profile looks as expected for users without a rank have been added.

Create ranking after first match

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/sites/profile.html

Design message if logged in player has never played a match

---

src/main/resources/static/js/ranking.js
src/main/resources/templates/sites/ranking.html

Search Button Fix

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/static/css/ranking.less
src/main/resources/templates/fragments/header.html
src/main/resources/templates/sites/matchresult.html
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html
src/test/java/de/adesso/kicker/user/UserControllerTest.java

Also Closes #235 and worked on better naming for message.properties

Fix responsiveness of ranking-table in ranking.html

---

src/main/resources/static/js/ranking.js

Fixed broken links of pager functions

---

src/main/resources/static/css/profile.less
src/main/resources/static/css/ranking.less
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html

Fixing error messages

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/error/404.html

Add 404 page

---

src/main/java/de/adesso/kicker/configurations/KeycloakSecurityConfig.java
src/main/java/de/adesso/kicker/user/controller/UserController.java
src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/static/css/profile.less
src/main/resources/static/css/ranking.less
src/main/resources/static/js/chartFillPlugin.js
src/main/resources/templates/js/profile.js
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html
src/test/java/de/adesso/kicker/user/StatisticDummy.java
src/test/java/de/adesso/kicker/user/TrackedStatisticDummy.java
src/test/java/de/adesso/kicker/user/UserControllerTest.java
src/test/java/de/adesso/kicker/user/UserDummy.java
src/test/java/de/adesso/kicker/user/service/StatisticServiceTest.java

Functionality of ChartJs user statisctics
Closes #194 
Closes #247

Chartjs statistics

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties

As Tom mentioned long time ago

Adjust Names

---

src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/email/verification.html
src/main/resources/templates/error/404.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/matchverification.html
src/main/resources/templates/fragments/message.html
src/main/resources/templates/sites/matchresult.html
src/main/resources/templates/sites/notificationresult.html
src/main/resources/templates/sites/profile.html
src/main/resources/templates/sites/ranking.html

Fix formatting of some HTML files.
Fix some mistakes with the message.properties.
Change normal HTML comments to Thymeleaf comments

Minor refactoring

---

src/main/resources/templates/sites/matchresult.html
src/main/resources/templates/sites/ranking.html

Show userId behind full name of users in search bars

---

src/main/java/de/adesso/kicker/user/controller/UserController.java
src/main/java/de/adesso/kicker/user/service/UserService.java
src/main/resources/messages.properties
src/main/resources/messages_de.properties
src/main/resources/templates/fragments/header.html
src/main/resources/templates/sites/matchresult.html
src/test/java/de/adesso/kicker/user/UserControllerTest.java

This adds a simple checkbox to the dropdown to toggle the receiving of emails.
Closes #275

Add checkbox to enable/disable emails

---

src/main/resources/static/css/matchresult.less
src/main/resources/templates/fragments/header.html
src/main/resources/templates/sites/matchresult.html

Notification dropdown is now right aligned on smaller screens.
The tooltip is placed properly on all sizes and with alerts.

Improve frontend for mobile devices

---

src/main/resources/static/css/header.less
src/main/resources/templates/fragments/header.html

This prevents the logo from appearing big at page load.
Closes #279

Set logo size in html instead of scss

---

src/main/java/de/adesso/kicker/notification/matchverificationrequest/service/VerifyMatchService.java
src/main/java/de/adesso/kicker/user/service/StatisticsService.java
src/main/resources/templates/error/404.html
src/main/resources/templates/fragments/header.html
src/test/java/de/adesso/kicker/notification/matchverificationrequest/service/VerifyMatchServiceTest.java

Fix method in form for toggling emails
Move side effects out of stream

Fix several minor issues

---

Dockerfile
README.md
experimental.Dockerfile
pom.xml

Decrease startup time and image size. Add experimental Dockerfile to cache maven dependencies.

Dockerfile updates

---

src/main/java/de/adesso/kicker/email/SendVerificationMailService.java
src/main/java/de/adesso/kicker/match/service/MatchService.java
src/main/java/de/adesso/kicker/user/service/UserService.java

These events include user creation, match creation and verification, and sending
email.
Closes #306

Add logging to certain events

---

src/main/java/de/adesso/kicker/configurations/KeycloakSecurityConfig.java
src/main/resources/application-prod.properties
src/main/resources/application.properties
src/test/java/de/adesso/kicker/match/controller/MatchControllerTest.java

Disables H2 Console specific configuration, removes old credentials, and updates tests to work with CSRF enabled.
Closes #307

Update config for production

---

src/main/resources/templates/js/profile.js

Adapted step size and min value for some charts.
